config:
  server: "127.0.0.1"
  port: "25"
  starttls: "no"
  username: ""
  password: ""

message:
  from: "test <test@example.com>"
  to: "test@example.com"
  subject: "TEST SUBJECT"
  body: "TEST MESSAGE"
